language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - sudo apt-get install -y texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra latexmk
script:
  - python deploy_gh_pages.py
