language: python
python:
  - "3.6"
addons:
  apt:
    update: true
    packages:
    - texlive-latex-base
    - texlive-fonts-recommended
    - texlive-fonts-extra
    - texlive-latex-extra
    - latexmk
    - enchant
cache:
  apt: true
  directories:
    - $HOME/.cache/pip
install:
  - pip install -r requirements.txt
script:
  - python deploy_gh_pages.py
